import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="w-full h-20 bg-white shadow-2xl relative z-50 border-gray-400">
          halow
        </div>
        <div className="min-h-screen">
          {children}
        </div>
        <Toaster />
        <Link href="https://github.com/dfi06" className="w-full h-40 bg-blue-400 p-16 flex flex-col  text-center">
          made w ♡ 
          <div>{`click me for my github`}</div>
        </Link >
      </body>
      
    </html>
  );
}
