import { Geist, Geist_Mono, Sora } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { Toaster } from "@/components/ui/sonner"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"], 

})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${sora.variable} font-sora`}
      >
        <div className="w-full h-16 bg-white shadow-2xl relative z-50 border-gray-400 text-black text-vorder font-bold p-4 text-xl flex justify-between" >
          <Link href="/" >🏠 Home</Link>
          <Link href="/#forms" className="pl-12">📝 Forms</Link>
          <Link href="#footer" className="text-white"> you found me!</Link>
        </div>
        <div className="min-h-screen">
          {children}
        </div>
        <Toaster />
        <Link id="footer" href="https://github.com/dfi06" className="w-full h-40 bg-blue-400 p-16 flex flex-col  text-center">
          ui is n̶o̶t̶ my passion, made w ♡ 
          <div>{`click me for my github`}</div>
        </Link >
      </body>
      
    </html>
  );
}
